apiVersion: v1
kind: Service
metadata:
  name: {{ include "lxbak.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lxbak.name" . }}
    helm.sh/chart: {{ include "lxbak.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "lxbak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
